option = {
  "version":{
    "code":"v1",
    "type":"Option"
  },
  "analyst":{
    "timestamp_last_change":"",
    "analyst":"",
    "controller":""
  },
  "internal_data":{
    "as_of_date":"",
    "internal_id":"",
    "bbg_id":"",
    "reuters_id":"",
    "wm_id":""
  },
  "id":{
    "isin":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "isin_2":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "isin_3":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "isin_4":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "isin_5":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "cusip_1":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "cusip_2":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "cusip_3":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "cusip_4":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "cusip_5":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "sedol_1":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "sedol_2":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "sedol_3":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "sedol_4":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "sedol_5":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "wkn":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "deloitte_internal_id":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "limpid_credits_id":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "bbg_ticker_1":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "bbg_ticker_2":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "bbg_ticker_3":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "reuters_ticker_1":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "reuters_ticker_2":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "reuters_ticker_3":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    }
  },
  "security":{
    "asset_name":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "type":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "subtype":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "status":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "position":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "issue_date":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "maturity":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "issue_currency":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "strike":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "exercise_type":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "underlying":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "value_of_one_point":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "contract_size":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
  },
  "country":{
    "domicile_code":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
    "risk_code":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    }
  },
  "other":{
    "complexity_class":{
      "rule_based":"",
      "manual_override":"",
      "comment":""
    },
  },
  "comments":{
    "general":""
  },
}

